language: python
python:
  - 2.7
  - 3.5
addons:
  apt:
    packages:
    - git
    - make
    - curl
    - xz-utils
    - file
    - pandoc
    - libboost-all-dev
    - language-pack-ja-base
    - language-pack-ja
    - ibus-mozc
    - gcc-5
    - g++-5
    - build-essential
    - swig
    sources:
    - ubuntu-toolchain-r-test
before_install:
  - sudo apt-get update -qq
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
  - sudo update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
  - mkdir ./target
  - export CC="gcc-5"
  - export CXX="g++-5"
  - export CFLAGS=-std=c++11
  - export CXXFLAGS=-std=c++11
  - sudo bash travis-mecab-install.sh
  - which mecab-config
  - sudo make install
  - git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
  - cd mecab-ipadic-neologd && echo yes | sudo ./bin/install-mecab-ipadic-neologd && cd ../
  - sudo juman -S
install:
  - python --version
  - python setup.py install
  - pip install coveralls coverage nose
script:
  - coverage run --source=JapaneseTokenizer setup.py test
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - kensuke.mit@gmail.com
    on_success: always
    on_failure: always